      PROGRAM ANAINT
      IMPLICIT NONE
      DOUBLE PRECISION JD,ET
      DOUBLE PRECISION STATE(6),PV(6),LT
      INTEGER J,K
      CHARACTER*18 BODIES(5)
      DATA BODIES/'VENUS BARYCENTER','EARTH BARYCENTER',
     *  'JUPITER BARYCENTER','SATURN BARYCENTER','CASSINI'/
      INTEGER STRLEN
      PARAMETER(STRLEN=32)
      CHARACTER*(STRLEN) ABCORR
      CHARACTER*(STRLEN) FRAME
C
      CALL FURNSH ( 'cassini.meta' )

      ABCORR='NONE'
      FRAME='J2000'
C
    1 READ(5,*,END=9999) JD,K,PV
      ET=86400.0D0*(JD-2451545.0D0)
      CALL SPKEZR(BODIES(K), ET, FRAME, ABCORR, 'SUN', STATE, LT)
      DO J=1,6
        PV(J)=PV(J)-STATE(J)
      END DO
      WRITE(6,1000) JD,K,PV
      GOTO 1
C
 9999 STOP
C
 1000 FORMAT(F14.6,1X,I2,6(1X,D20.12))
C
      END
